import { ComponentDefinition } from '../models/component.model';

export const COMPONENT_DEFINITIONS: ComponentDefinition[] = [
  {
    id: 'container',
    type: 'Container',
    name: 'Container',
    icon: 'view_quilt',
    category: 'layout',
    canHaveChildren: true,
    properties: [
      { name: 'display', type: 'select', defaultValue: 'flex', options: ['flex', 'grid', 'block'] },
      { name: 'flexDirection', type: 'select', defaultValue: 'row', options: ['row', 'column'] },
      { name: 'gap', type: 'spacing', defaultValue: 16 },
      { name: 'padding', type: 'spacing', defaultValue: 16 },
      { name: 'backgroundColor', type: 'color', defaultValue: '#ffffff' },
    ],
    defaultProps: {
      display: 'flex',
      flexDirection: 'row',
      gap: 16,
      padding: 16,
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'text',
    type: 'Text',
    name: 'Text',
    icon: 'text_fields',
    category: 'content',
    canHaveChildren: false,
    properties: [
      { name: 'content', type: 'string', defaultValue: 'Text content', validation: { required: true } },
      { name: 'fontSize', type: 'typography', defaultValue: 16 },
      { name: 'fontWeight', type: 'select', defaultValue: 'normal', options: ['normal', 'bold', '100', '300', '500', '700', '900'] },
      { name: 'color', type: 'color', defaultValue: '#000000' },
      { name: 'textAlign', type: 'select', defaultValue: 'left', options: ['left', 'center', 'right', 'justify'] },
    ],
    defaultProps: {
      content: 'Text content',
      fontSize: 16,
      fontWeight: 'normal',
      color: '#000000',
      textAlign: 'left',
    },
  },
  {
    id: 'image',
    type: 'Image',
    name: 'Image',
    icon: 'image',
    category: 'media',
    canHaveChildren: false,
    properties: [
      { name: 'src', type: 'string', defaultValue: 'https://via.placeholder.com/300', validation: { required: true } },
      { name: 'alt', type: 'string', defaultValue: 'Image' },
      { name: 'width', type: 'number', defaultValue: 300, validation: { min: 0 } },
      { name: 'height', type: 'number', defaultValue: 200, validation: { min: 0 } },
      { name: 'objectFit', type: 'select', defaultValue: 'cover', options: ['cover', 'contain', 'fill', 'none'] },
    ],
    defaultProps: {
      src: 'https://via.placeholder.com/300',
      alt: 'Image',
      width: 300,
      height: 200,
      objectFit: 'cover',
    },
  },
  {
    id: 'button',
    type: 'Button',
    name: 'Button',
    icon: 'smart_button',
    category: 'form',
    canHaveChildren: false,
    properties: [
      { name: 'label', type: 'string', defaultValue: 'Click me', validation: { required: true } },
      { name: 'variant', type: 'select', defaultValue: 'primary', options: ['primary', 'secondary', 'outline'] },
      { name: 'size', type: 'select', defaultValue: 'medium', options: ['small', 'medium', 'large'] },
      { name: 'backgroundColor', type: 'color', defaultValue: '#007bff' },
      { name: 'textColor', type: 'color', defaultValue: '#ffffff' },
    ],
    defaultProps: {
      label: 'Click me',
      variant: 'primary',
      size: 'medium',
      backgroundColor: '#007bff',
      textColor: '#ffffff',
    },
  },
  {
    id: 'input',
    type: 'Input',
    name: 'Input',
    icon: 'input',
    category: 'form',
    canHaveChildren: false,
    properties: [
      { name: 'placeholder', type: 'string', defaultValue: 'Enter text...' },
      { name: 'type', type: 'select', defaultValue: 'text', options: ['text', 'email', 'password', 'number'] },
      { name: 'label', type: 'string', defaultValue: 'Input Field' },
      { name: 'required', type: 'boolean', defaultValue: false },
    ],
    defaultProps: {
      placeholder: 'Enter text...',
      type: 'text',
      label: 'Input Field',
      required: false,
    },
  },
  {
    id: 'form',
    type: 'Form',
    name: 'Form',
    icon: 'dynamic_form',
    category: 'form',
    canHaveChildren: true,
    properties: [
      { name: 'action', type: 'string', defaultValue: '/submit' },
      { name: 'method', type: 'select', defaultValue: 'POST', options: ['GET', 'POST'] },
      { name: 'gap', type: 'spacing', defaultValue: 16 },
    ],
    defaultProps: {
      action: '/submit',
      method: 'POST',
      gap: 16,
    },
  },
];
